### ISSUE TITLE
Terrible dependencies being terrible

### ISSUE THREAD

**Issue by Silic0nS0ldier** [userfrosting/browserify-dependencies#9]
There are some shockingly bad instances of spec violation in some packages that can cause issues with a library as "greedy" as this.

Take https://github.com/daneden/animate.css , it specifies CSS as the main module entrypoint in `package.json`.

To handle terrible scenarios like this, a refactor will be required. Along with some form of result reporting on completion.

**Comment by alexweissman** [comment]
Which spec is the package violating?

**Comment by Silic0nS0ldier** [comment]
Much as I'd like to point to some formal spec, all that exists is informal. If Node JS tries to load a package (e.g. `require("browserify-dependencies")`) it will look at `package.json` for the `main` field and will run the files content as though it were JavaScript. Fairly fundamental to the Node JS ecosystem, which was created with only JS in mind.

Some unofficial standards have formed over time to account for scenarios such as vendor CSS (with NPM encouraging them, citing Node JS becoming the defacto-standard web app development tool). Some however decided (perhaps due to being unfamiliar with the Node JS ecosystem) to use `main` as a field for CSS tooling, which ends up presenting problems later on with certain setups (such as the scenario here). In practise, it boils down to an unnecessary shortcut in most cases as alternatives that avoid the problem exist (and are encouraged by the current ecosystem).

🤔 It does occur to me however that a scenario may have been missed in this package. No `main` implies a default value of `index.js`, which we currently don't handle (silently skipping it).

**Comment by alexweissman** [comment]
That makes sense. It doesn’t look like this package has an `index.js`, but would it be simple to create one? Or should we talk to the browserify team about what the best way to load packages like this would be (Create a wrapper, use a browserify transformation; etc)?

**Comment by Silic0nS0ldier** [comment]
Browserify already has transform plugins you can use for that, and the way this library is written lets you pass them in.

However as every package gets processed, it is preferable that a way to just "shrug it off" be added, as we cannot be sure a package is designed to be consumed the standard way (we already have partial handling of this for when there is no main file, its just imperfect).

I know what changes need to be made to see this resolved. Only constraint here is my time, I'll prioritise this given it is a blocker for some.

**Comment by Silic0nS0ldier** [comment]
Work-around developed. UserFrosting will need to make some changes to handle this.
